### ISSUE TITLE
Extending the library for other exchanges

### ISSUE THREAD

**Issue by cymp** [CCob/bittrex4j#17]
Hello, 

Would you have any guidelines if one wants to extend this library to another signalR exchange?

Thanks

**Comment by CCob** [comment]
Hi There,

Take a look at my fork of the original signalr library by Microsoft - https://github.com/signalr4j/signalr4j.  I wouldn't use their original one as it hasn't been maintained and didn't work correctly.  The fork I made is not much better, but at least it was fixed and the web sockets transport mechanism now works.

SignalR concepts should be the same, so you'll need to create a HubConnection the exchange in question.  The hub name and events and methods are likely to be different of course.

Hope that helps.

**Comment by CCob** [comment]
Hi cymp, I tend to charge  by hour which can be cost p

**Comment by cymp** [comment]
That doesn't tell me how much that would be :)

**Comment by CCob** [comment]
I can't tell you how long it would take as it depends on what you would want.  Go through the commits of bittrex4j and that should give you an idea of scale.  You may for example want to get the bulk of it done then take over the project from there.  I would say there is at least 20 hours of coding to get the project to a usable level.

**Comment by cymp** [comment]
Ok thanks for your estimation @CCob !

**Comment by CCob** [comment]
Have you seen the [XChange ](https://github.com/knowm/XChange) Java library.  It has a wide range of exchange support, but I don't think they support web sockets

**Comment by cymp** [comment]
Yes, I'm quite active on this library. For its websocket part, you can check https://github.com/bitrich-info/xchange-stream.

**Comment by CCob** [comment]
If you are familiar with those projects, wouldn't it make more sense for you to just add cryptopia to the xchange-stream project?

**Comment by cymp** [comment]
Sure, but I can’t find time to do it atm...
