### ISSUE TITLE
Websocket method 'SubscribeToSummaryDeltas'

### ISSUE THREAD

**Issue by c0nf1ck** [CCob/bittrex4j#2]
First of all, thanks for this great library.

There's a way to subscribe to the summary deltas to get ticks of all markets instead of subscribing to all markets and then connect to the websocket?
If so, can you provide a simple example?

Thanks

**Comment by CCob** [comment]
Not quite sure what your asking, but I'll take a guess at answering

SubscribeToSummaryDeltas was an automatic push as soon as you connect to the web socket, so there was no need to have a subscribeToSummaryDeltas method.  I believe recently Bittrex changed this behavior recently and you specifically need to invoke a web socket method once connected if you are interested in the summary deltas.  

I haven't got around to exposing a method on the BittrexExchange class yet though.  Shouldn't be too difficult but have needed to work on the CloudFlare DDoS protection that the API had.  

I finished that over the weekend so when I get time I'll see if I can add it.  Also happy to accept a pull request if you have the time to add the functionality 😉

**Comment by CCob** [comment]
I have published a 1.0.3-SNAPSHOT build which contains the b2d157b7ff27b799c81a31d48e22bb411c01ca33 commit.  Let me know if this works for you.

**Comment by c0nf1ck** [comment]
I forked the repository and did exactly as your commit. 

That's exactly what i want. Thanks anyway.

**Comment by CCob** [comment]
Great.  I'll release 1.0.3 soon so you can re-link your dependency to the central repos again.
