### ISSUE TITLE
nonce or nounce?

### ISSUE THREAD

**Issue by marinatraisler** [CCob/bittrex4j#22]
Hey,
I've seen that some of the dao are using nounce and some nonce.. 
and also, after looking at the api nonce should be int, but you used long (for example: UpdateExchangeState)
can you please tell me what am I missing?

thanks

**Comment by marinatraisler** [comment]
so we still need to use both APIs? the original api and the web socket api? I didn't find any documentation about this

**Comment by CCob** [comment]
No, you can choose either the REST API or Websocket API.  But   the REST API has rate limits as I beleive Bittrex would prefer developers to use the websocket API
