### ISSUE TITLE
listeners and logic

### ISSUE THREAD

**Issue by marinatraisler** [CCob/bittrex4j#24]
Hey,
I take for example this listener:
private Observable<ExchangeSummaryState> exchangeSummaryStateBroker = new Observable<>();

why do we need a list of listeners? why it can't be just one?
same question goes to all the listeners..

another question:
what's your opinion regarding BittrexExchange. show it be one thread for marketdata and one for trading? or one thread can handle both?

**Comment by marinatraisler** [comment]
thanks for the explantions 👍

**Comment by CCob** [comment]
No problem, I'll close for now.
