### ISSUE TITLE
BittrexExchange.queryExchangeState fails

### ISSUE THREAD

**Issue by bezratigreeninvestment** [CCob/bittrex4j#26]
Hey guys,

Been integrating this library into a project of mine.
All BittrexExchange class methods that I have used worked flawlessly for me: connectToWebSocket, onOrderStateChange,  onBalanceStateChange, onUpdateExchangeState, subscribeToExchangeDeltas.

However, queryExchangeState fails, with this exception: 
09:53:33.870 [Thread-8] ERROR com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $

It seems that the full order book response can't be properly parsed.
The exception is occurring in the signalr4j v2.0.3 library, class HubProxy, line 157:
resultObject = HubProxy.this.mConnection.getGson().fromJson(result.getResult(), resultClass);

The code is trying to parse this payload [https://goo.gl/Hyd92B](https://goo.gl/Hyd92B) into a  com.google.gson.internal.LinkedTreeMap

I tried to manually parse that payload myself by base64 decoding it then unzipping it, but unzipping fails.

Could you please tell me what could be the cause for this issue?

Also, is calling the REST API order book link a viable workaround?
Can I use the REST API response nonce to construct my local orderbook with UpdateExchangeState events?

Your help will be most appreciated.

Regards,
I.

**Comment by CCob** [comment]
Great, I'm glad it's working out for you.  That issue is fixed in 1.0.10-SNAPSHOT, see #23.  I haven't made a 1.0.10 release yet as I haven't had the time.  Hopefully this weekend I'll be able to get it done but unfortunately my paid job is taking up more time that I'd like.

Let me know if 1.0.10-SNAPSHOT works for you too.

**Comment by bezratigreeninvestment** [comment]
Wow, that was a quick reply!!!
I'll try it out and get back to you.

Best,
I.

**Comment by CCob** [comment]
It's only me working on the library, so your donation is certainly appreciated 👍

**Comment by CCob** [comment]
@bezratigreeninvestment - As you have been so kind to donate, I have just published the official 1.0.10 release which should include the fix for `queryExchangeState`.  So you shouldn't need to use the SNAPSHOT build.

**Comment by bezratigreeninvestment** [comment]
@CCob, my small gift was really nothing compared to the value of your work. This project has been well written and has tremendous utility.
I was wondering, do you have experience programming clients (specially WS) for other major exchanges?
Would you consider doing so in exchange of some compensation?
Let me know so I can plan my project accordingly.
Regards,
I.

**Comment by CCob** [comment]
I have yes.  I have created a bot which is not open source that uses the bittrex4j library among others.  What exchange are you interested in creating a library for?

**Comment by bezratigreeninvestment** [comment]
For now I am eyeing Poloniex and Bitstamp.
Also Kraken if there's a way to use a WS API (which currently they don't
offer).
Maybe there are already existing java clients for their REST/WS/FIX apis, I
haven't made my research yet, but getting new integrations to work is also
a challenge every time.
Eventually, I my goal is to integrate with all "legit" exchanges with
considerable volume for the "legit" coins.

**Comment by CCob** [comment]
Have you seen XChange - https://github.com/knowm/XChange?  It has support for a ton of exchanges via REST.  It didn't have Websocket support for bittrex, which is why I created this library
