### ISSUE TITLE
logging pollutions 

### ISSUE THREAD

**Issue by szd116** [CCob/bittrex4j#27]
When I subscribed to all market names, i'm getting lots of redundant messages such as following I think we should change the following message to DEBUG or trace ? I think at INFO level this is polluting the log file. 
Is there a config files included in jar ? maybe I can default the logging on my end to Warning or Error for now, can you tell me where the config file is ? I can't seem to find it. Thanks. 
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message

**Comment by CCob** [comment]
Yes, I agree with this.  Unfortunately these are from inside the signalr library and have not been done in a good way.  I use the library under Spring and can control the log levels for different loggers though application.properties.  And the ' com.github.ccob.bittrex4j.BittrexExchange.WebSockets' logger in particular I set to WARN level

**Comment by szd116** [comment]
Thank you for your response. I am building a system from scratch so I don't have a safety net type of config file that would capture all the loggers. This may not be the best place to ask the question but I have tried quite a few different config files but non of them changes the logging level of signalr, any suggestions ? Thank you in advance.

**Comment by CCob** [comment]
Internally bittrex4j uses slf4j.  But this is abstracted around numerous logging engines.  So it depends on what you are using?

http://saltnlight5.blogspot.com/2013/08/how-to-configure-slf4j-with-different.html

The a look here, I use the logback engine which can be configured with a logback.xml being present on the root of the classpath.

**Comment by CCob** [comment]
Great, I'll close the ticket.
