### ISSUE TITLE
No Nounce in Rest API

### ISSUE THREAD

**Issue by szd116** [CCob/bittrex4j#28]
I'm making a call to bittrexExchange.getMarketOrderBook("USDT-LTC").getResult(), however this order book unlike the call to queryExchangeUpdate, doesn't get me the Nounce which I need to update the buy and sell order book. Is this a bug ? Thanks.

**Comment by CCob** [comment]
Nope, this is expected.  Nonce updates only come from `queryExchangeState` web socket method call and `updateExchangeState` event notifications on the websocket and work in tandem.  The REST API call `getMarketOrderBook` has no such relationship unfortunately, it just shares the same DTO.
