### ISSUE TITLE
subscription to connection errors

### ISSUE THREAD

**Issue by aleqs** [CCob/bittrex4j#3]
first of all, great project. thank you for putting your time and effort into this

currently, the BittrexExchange class doesn't seem to support connection error/close listeners. hubConnection.error() is only used internally in the class and not exposed to users, and it would be very useful to have an API similar to defining a runnable in connectToWebSocket()

**Comment by CCob** [comment]
Sure I'll take a look at exposing this.  I suppose the idea behind this was to reconnect without library user being aware but I suppose it would be handy for library users to know and error has occurred

**Comment by CCob** [comment]
I've added a new `onWebsocketError` function that allows you to register an observer for websocket errors.  Let me know if this does the trick for you.

**Comment by CCob** [comment]
You should be able to check out fixes for both #3 and #4 in the latest 1.0.4-SNAPSHOT

**Comment by aleqs** [comment]
this is pretty good, thank you

another thing that would be nice to improve (that falls outside of the scope of the issue though) is for users to be able to manage reconnects better - i.e. pass reconnectionPeriodMillis either via constructor or via a setter. and say if the value is negative, no reconnection is scheduled - but the user can take their own action by adding the error listener via the api you just added

**Comment by CCob** [comment]
Agreed, there are a few usability improvements that need doing like that.  Early days yet.

**Comment by CCob** [comment]
Implemented in release 1.0.4
