### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by anhtuantt** [CCob/bittrex4j#30]
Thank you very much for excellent library. I used it in my trading bot with the highly stable. For now I want to get orderbooks of multiple markets, for example BTC-XRP and BTC-ETH? Could I do this?

**Comment by CCob** [comment]
Glad you like it.  If you want real time order book info you simply call `subscribeToExchangeDeltas` multiple times per market.  Once you have a callback confirming subscription you can call `queryExchangeState` to get a snapshot of the order book (max 500 orders).  `queryExchangeState` result will give you a nonce value, then the `onUpdateExchangeState` callback will give you updates to the order book also with a nonce value.  These should be processed sequentially.  If you lose sync the process starts again.

**Comment by anhtuantt** [comment]
Thanks, Let me get start and have a feedback soon.
