### ISSUE TITLE
HubConnection - Error:

### ISSUE THREAD

**Issue by sf202020sf** [CCob/bittrex4j#31]
When I execute the Example i get the following errors (ShowRealtimeFills.java):

efault] [Thread-4] ERROR c.g.c.b.BittrexExchange.WebSockets - HubConnection - Error: java.lang.reflect.InvocationTargetException 

What does that mean?

I opend it several times - is it a response from Bittrex?

**Comment by CCob** [comment]
This is usually because there is an exception occurring in one of your callbacks.  The InvocationTargetException should have a cause that will point you in the right direction
