### ISSUE TITLE
Question on fills

### ISSUE THREAD

**Issue by szd116** [CCob/bittrex4j#33]
Hi CCob,
Thank you for your latest release. I have a few questions on your latest release. 
1. From the orderDelta, is there anyway to figure out which side of the order is this BUY or SELL ?
2. If the answer to question 1 is No, then I would need to keep track of the orders locally, so is it possible that I would get a fill first then the UUID from submitting the order comes later ?

Thank you again for your hard work.

**Comment by CCob** [comment]
Take a look here - https://bittrex.github.io/#order-delta---uo 

Does `OrderType` or `Type` within the object help?

**Comment by szd116** [comment]
I think I overlooked a few minor details, orderDelta.getType is the order status and orderDelta.getOrder.GetType is the order side info. Thanks CCob. By the way, is IOC order type will be implemented soon ? I think Bittrex supports it. Thanks again for all the hard work !

**Comment by szd116** [comment]
https://github.com/Bittrex/bittrex.github.io

In the link above under the section Appendix A: Minified JSON Keys
you will find "K" = "ImmediateOrCancel"

Thanks.

**Comment by CCob** [comment]
Ah right.  Unfortunately you can only submit new orders through their REST API, which doesn't support it yet.  So only limit orders so far.

**Comment by szd116** [comment]
Cool. Thanks CCob.

**Comment by szd116** [comment]
Issued resolved. order side information is under orderDelta.getOrder.getType
