### ISSUE TITLE
Null MarketName

### ISSUE THREAD

**Issue by cymp** [CCob/bittrex4j#37]
Hello @CCob 

I am receiving a lot of "null" values for updateExchangeState, have you seen this before?

![image](https://user-images.githubusercontent.com/3685318/42411848-bb56ca54-8203-11e8-8fb3-dcbd28ce1e68.png)

So I don't know on which order book I should put these received updates on.

**Comment by cymp** [comment]
It looks like the orderbooks snapshots have the correct market name filled, but the updates don't.

**Comment by CCob** [comment]
Do you see it every update or only some of them?  If it's sporadic, then that can only be the data that is send from Bittrex itself.

**Comment by cymp** [comment]
I can see them at every update. The workaround would be to have one connection per book, but I don’t know how Bittrex would react.

**Comment by CCob** [comment]
I'd be surprised if the data is not inside the minified JSON from Bittrex.  I'm tied up right now, so am no able to look into it.  I'm guessing it's a de-serialization issue

**Comment by cymp** [comment]
I've had troubles trying to understand how the signalR Json is received, it looked encoded when I tried to debug it. I haven't had more time to spend on this unfortunately.
