### ISSUE TITLE
removal of finalize()

### ISSUE THREAD

**Issue by aleqs** [CCob/bittrex4j#4]
this is a minor thing, but it would be cleaner to either remove finalize() from BittrexExchange altogether or implement Closeable instead. i think it is expected that users can take care of resource management themselves :)

**Comment by CCob** [comment]
Yes, this certainly would make more sense in modern day java.  I'll caught up in a few other things this coming week so hopefully get to in next week.  Happy to take a PR too 😉

**Comment by CCob** [comment]
Just pushed this change to develop, will be in the next release

**Comment by aleqs** [comment]
thank you, looks good!
