### ISSUE TITLE
Websocet  subscribeToExchangeDeltas  method

### ISSUE THREAD

**Issue by CheremisinVlad** [CCob/bittrex4j#40]
Hello!Fist of all thanks for great work.
I have one stupid question.
When i use **subscribeToExchangeDeltas()**  method , how can i recieve data when bittrex push it?

**Comment by CCob** [comment]
Have you look at the examples, these should show everything you need.  But essentially you need to register callback methods similar to below first 

```java
bittrexExchange.onUpdateExchangeState(updateExchangeState -> {
   //your code on new event here
}) 
```

Then during the connectToWebsocket callback you would register your interest in a specific market like this

`bittrexExchange.subscribeToExchangeDeltas("BTC-ETH", null);`

**Comment by CheremisinVlad** [comment]
Thanks a lot for your answer.It's clear now. Pls close this issue.
