### ISSUE TITLE
Bittrex major system upgrade Hub Connection Error

### ISSUE THREAD

**Issue by CheremisinVlad** [CCob/bittrex4j#43]
Hello,Coob!  One more time thanks you for your work. I use your library for my project and it worked well. But now I encounter with this problem

> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.reflect.InvocationTargetException
> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.reflect.InvocationTargetException
> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.reflect.InvocationTargetException
> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.Exception: Connection closed
> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.Exception: Connection closed
> ERROR WebSockets [SignalRLoggerDecorator.java:30] HubConnection - Error: java.lang.Exception: Connection closed

 This is my code:

```
//subscribe for each market
exchange.connectToWebSocket(()->{
            getBittrexMarkets().forEach(market->{
                exchange.subscribeToExchangeDeltas(market,null);
            });
        });
```
and then  i use this

```
exchange.onUpdateExchangeState(orderBook->{
//some logic
});
```
I've added last snaphot 1.0.11-SNAPSHOT from sonatype.

Is any thoughts what i'm doing wrong or maybe it relates with Bittrex updates?
Thanks in advance.

**Comment by CCob** [comment]
```InvocationTargetException``` usually occurs when an exception is raised inside an event handler.  Do you have a top level exception handler in your onUpdateExchangeState function, if not and an exception occurs you will usual get this.  Catching inside your inUpdateExchangeState handler should show you the original exception

**Comment by CCob** [comment]
1.0.11 just released that should fix breaking API changes from Bittrex.
