### ISSUE TITLE
Bittrex alpha V3 is out

### ISSUE THREAD

**Issue by szd116** [CCob/bittrex4j#48]
I'm not sure how difficult it is merge v2 to v3, but the developers from Bittrex said that V2 will be phased out very soon. @CCob would you support V3 ? I really appreciate your effort.

**Comment by CCob** [comment]
Do you have any information on the v3 API?

**Comment by szd116** [comment]
here's the link 

https://bittrex.github.io/api/v3

**Comment by szd116** [comment]
@CCob what do you think ? is it can be easily implemented ? Thanks.

**Comment by CCob** [comment]
Looks a bit different to be honest

**Comment by CCob** [comment]
Not technically challenging, but most of the API calls and DTO's would need to change

**Comment by szd116** [comment]
V2 sounds like it's something they would disband pretty quickly once V3 comes to fruition. V2 to be honest has lots of issues.
