### ISSUE TITLE
Spams on the UpdateExchangeStateListener 

### ISSUE THREAD

**Issue by revidee** [CCob/bittrex4j#5]
Hey man, first of all, nice job with the library.
Everything went well the past days, but today something strange is happening.

After subscribing to the ExchangeDeltas and queryExchangeState to get the recent orderbook like so:

//Connect to Websocket and subscribe to the given Pairs

            bittrexExchange.connectToWebSocket( () -> {
                for(Map.Entry<CurrencyPair, OrderBook> currencyPair : this.getCurrencyPairs().entrySet()){
                    bittrexExchange.subscribeToExchangeDeltas(currencyPair.getKey().toString("-"),(success -> {
                        if(success)
                            bittrexExchange.queryExchangeState(currencyPair.getKey().toString("-"), getUpdateExchangeStateListener(currencyPair.getKey().toString("-")));
                    }));
                }
            });

Note that this is only being called once
In order to keep em up-to-date, I check the Nounce and interpret the buys&sells updates.

I get those debug message (made by myself in the onUpdateExchangeState lamda /onQueryExchangeStateListener )

> Received full up-to-date Orderbook for BTC-CVC. Nounce: 309736
> Received full up-to-date Orderbook for ETH-CVC. Nounce: 309904
> Received full up-to-date Orderbook for BTC-ETH. Nounce: 468270
> BTC-CVC: 309737
> BTC-ETH: 468271
> BTC-CVC: 309738
> BTC-ETH: 468272
> BTC-CVC: 309739
> BTC-ETH: 468273
> BTC-ETH: 468274
> BTC-ETH: 468275
> BTC-CVC: 309740
> BTC-ETH: 468276
> BTC-CVC: 309741
> BTC-ETH: 468277
> <all correct to this tick>
> Received full up-to-date Orderbook for BTC-CVC. Nounce: 309740
> Received full up-to-date Orderbook for ETH-CVC. Nounce: 309904
> Received full up-to-date Orderbook for BTC-ETH. Nounce: 468276
> <why the hell do I receive another queryExchangeState response??>

some more of these messages

> oldNounce: 468079, new: 468289
> BTC-ETH: wrong nounce, waiting for update
> BTC-CVC: 309716
> BTC-ETH: 468080
> Received full up-to-date Orderbook for BTC-CVC. Nounce: 309750, test: null
> Received full up-to-date Orderbook for ETH-CVC. Nounce: 309912, test: null
> Received full up-to-date Orderbook for BTC-ETH. Nounce: 468289, test: null
> Received full up-to-date Orderbook for BTC-CVC. Nounce: 309750, test: null
> Received full up-to-date Orderbook for BTC-ETH. Nounce: 468289, test: null
> Received full up-to-date Orderbook for BTC-CVC. Nounce: 309750, test: null
> Received full up-to-date Orderbook for BTC-ETH. Nounce: 468289, test: null
> ETH-CVC: 309913
> ETH-CVC: 309913
> oldNounce: 309913, new: 309913
> ETH-CVC: 309913
> oldNounce: 309913, new: 309913
> ETH-CVC: wrong nounce, waiting for update
> ETH-CVC: wrong nounce, waiting for update
> BTC-CVC: 309751
> BTC-CVC: 309751
> oldNounce: 309751, new: 309751
> BTC-CVC: wrong nounce, waiting for update
> BTC-CVC: 309751
> oldNounce: 309751, new: 309751
> BTC-CVC: wrong nounce, waiting for update

Espacially here, one can see, with only subscribing to one pair, that I receive updates for 2 nounces:

> ETH-TIX: 272479
> oldNounce: 275649, new: 272479
> ETH-TIX: wrong nounce, waiting for update
> Received full up-to-date Orderbook for ETH-TIX. Nounce: 272479
> Received full up-to-date Orderbook for ETH-TIX. Nounce: 272479
> Received full up-to-date Orderbook for ETH-TIX. Nounce: 272987 <-- updates the nounce to this value
> ETH-TIX: 274596 <-- this is for an "old" state!
> oldNounce: 272987, new: 274596
> ETH-TIX: wrong nounce, waiting for update
> ETH-TIX: 272085 <-- this too!

After the initial phase, the frequency of onQueryExchangeStateListener calls increase.
What I noticed:

- I still receive updates for the old nounce 

- I also receive updates for the new nounce (Double updates with different nounces, everything else identically)

Even though I called bittrexExchange.queryExchangeState(..) only once.
These "auto" updates are happening today for the first time without modifying the core connection to the websocket.

How could these happen? Tried "downgrading" to 1.0.3 without success, using 1.0.4-SNAPSHOUT and 1.0.4 - same problem.

Maybe Bittrex related or is there anything i could try?

**Comment by revidee** [comment]
Update: Found the culprit:

                   if(updateExchangeState.getFills().length > 0) {
                        new Thread(() -> {
                            double volume = Arrays.stream(updateExchangeState.getFills()).mapToDouble(Fill::getQuantity).sum();
                            double price = Arrays.stream(updateExchangeState.getFills()).mapToDouble(Fill::getPrice).average().getAsDouble();
                            affectedOrderbook.updateVolume(volume, price);
                        }).start();
                    }

When not using a new Thread, you get the situation above. But when you do, it works. Strangely.

**Comment by CCob** [comment]
Glad you are finding a use for it

One thing to be wary of which I'm still working on, when there is a problem on the web socket, for example, when the error handler fires, internally bittrex4j reconnects which will re-fire the connected handler.  Now what I have noticed sometimes that on reconnect you seem to get 2 sets of nonces for the same market, one from the previous connection state and on from the reconnected one.

I'm not sure why this is yet because on reconnect the previous websocket is deleted and a new one is used.

**Comment by revidee** [comment]
Do you terminate the old connection first? Not that the same UDP endsocket is being used or something like that.

**Comment by CCob** [comment]
Yes, basically startConnection is called again once an unrecoverable error is detected.

https://github.com/CCob/bittrex4j/blob/4352355ab6aca1b27d06846e0e6e5dab4b938672/src/main/java/com/github/ccob/bittrex4j/BittrexExchange.java#L202

**Comment by revidee** [comment]
My issue seems to be releated to messing with the fills in the subscribeToExchangeListener. But it's funny since I only read data from the fills array.

Like I said, if I thread the reading operation it works perfectly well. If it runs in the same thread (maybe time-related?) it doesn't work and I get spams of onQueryExchange callbacks.

Maybe your problem is kind of related, a timing issue or something.

**Comment by CCob** [comment]
Found out my problem.  All boils down to the java signalr library that M$ wrote.  It's junk in reality.  If the web socket times out (no packets after 20s) then the signalr library internally will try to regain the connection using the same connection id.  But unfortunetly the signalr library doesn't clean up the previous web socket connection correctly, so if that also recovers you get notifications from both web sockets.

**Comment by CCob** [comment]
Fixed in 1.0.6 Release
