### ISSUE TITLE
Bittrex is changing their format

### ISSUE THREAD

**Issue by cymp** [CCob/bittrex4j#53]
Hello,

I am now getting: 

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "FillUuid" (class com.github.ccob.bittrex4j.dao.Fill), not marked as ignorable (17 known properties: "Rate", "FI", "Total", "OrderType", "Price", "Quantity", "TimeStamp", "Id", "FillType", "fillId", "total", "orderType", "quantity", "timeStamp", "id", "fillType", "price"])
at [Source: (org.apache.http.client.entity.DeflateInputStream); line: 1, column: 216] (through reference chain: com.github.ccob.bittrex4j.dao.UpdateExchangeState["f"]->java.lang.Object[][0]->com.github.ccob.bittrex4j.dao.Fill["FillUuid"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)

It looks like there is a need to adjust the parameters...

**Comment by CCob** [comment]
Happy to take a pull request and submit to maven.

**Comment by cymp** [comment]
@CCob 
PR created: https://github.com/CCob/bittrex4j/pull/54
Bittrex is currently working on their API.

**Comment by cymp** [comment]
@CCob 
It looks like you merged my PR, but I can't see https://github.com/CCob/bittrex4j/pull/54/commits/2386b95e69526c4c89188a6bc44940566ae93584 merged on the source code. Did I miss something?

**Comment by davidjirovec** [comment]
Are you looking at master branch? PRs were merged into develop branch.

**Comment by CCob** [comment]
Will be merged into master when a maven release is cut.  Will hopefully have some time mext week

**Comment by cymp** [comment]
Ok thanks

**Comment by CCob** [comment]
1.0.12 release should now be on maven.
