### ISSUE TITLE
Unit tests for 1.0.13-SNAPSHOT broken

### ISSUE THREAD

**Issue by jklappenbach** [CCob/bittrex4j#58]
-> % gradle build

> Task :test

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.DepositAddress] FAILED
    pl.pojo.tester.internal.GetOrSetValueException at DaoTests.java:57
        Caused by: java.lang.NoSuchFieldException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.OrderBookEntry] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Tick] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Currency] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.MarketSummaryResult] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Balance] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Ticker] FAILED
    pl.pojo.tester.internal.GetOrSetValueException at DaoTests.java:57
        Caused by: java.lang.NoSuchFieldException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.UpdateExchangeState] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.BalanceDelta] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.WithdrawalDeposit] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.CompletedOrder] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.WalletHealth] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.MarketSummary] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.MarketOrdersResult] FAILED
    pl.pojo.tester.internal.GetOrSetValueException at DaoTests.java:57
        Caused by: java.lang.NoSuchFieldException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.OrderBook] FAILED
    pl.pojo.tester.internal.GetOrSetValueException at DaoTests.java:57
        Caused by: java.lang.NoSuchFieldException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.WalletHealthResult] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Deltas] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.MarketOrder] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Order] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Market] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.UuidResult] FAILED
    pl.pojo.tester.internal.GetOrSetValueException at DaoTests.java:57
        Caused by: java.lang.NoSuchFieldException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.OrderDelta] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Response] FAILED
    java.lang.NullPointerException at DaoTests.java:57

com.github.ccob.bittrex4j.dao.DaoTests > shouldImplementDaoPojoGetters[class com.github.ccob.bittrex4j.dao.Fill] FAILED
    java.lang.NullPointerException at DaoTests.java:69

91 tests completed, 24 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/julian/code/java/bittrex4j/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
8 actionable tasks: 1 executed, 7 up-to-date

I can still build the project without tests, and use that.  Any plans of fixing this, or bringing 1.0.13 to Maven Central?

Anything I can do to help?

**Comment by CCob** [comment]
Sorry, missed this issue.  Not got a lot of time recently to keep bittrex4j maintained.  Happy to take a PR and merge though

**Comment by jklappenbach** [comment]
No worries.  Given their policies on API rate limiting, and the small number of coins they support, I decided against them.

Also, their choice of using a MS based framework for websockets was regrettable.  The API doesn’t even work with the Java libraries currently available in Maven.
