### ISSUE TITLE
V2 issues

### ISSUE THREAD

**Issue by norbertas-gaulia** [CCob/bittrex4j#6]
Hi, thanks for this great library, just let you know that i'm running into issues while using V2 api, seems like data returned from bittrex is sometimes  random, thats what i'm getting for btc orderbook:
https://puu.sh/z9ifx/fd9c261c4a.png

V1.1 is pretty stable so far. I would suggest completely get rid of V2 until it's officially documented, otherwise bot will loose a lot of coins.

**Comment by CCob** [comment]
I have noticed this too!

![image](https://user-images.githubusercontent.com/3064210/35388238-dbf2bf98-01ca-11e8-9103-9a62b79203dc.png)

I think they have some kind of caching issue on the v2 API's but nobody seems to care on the api-developers channel on slack.

I'll look at switching the v2 endpoints to v1 when I get a chance.
