### ISSUE TITLE
sellLimit error

### ISSUE THREAD

**Issue by LowSkiII** [CCob/bittrex4j#7]
After several tries create sell order with sellLimit and getting QUANTITY_NOT_PROVIDED error from bittrex I looked into code and found this:
buyLimit
```
...
withArgument("quantity",Double.toString(quantity))
...
```
sellLimit
```
...
withArgument("quantity",String.format("%f",quantity))
...
```
buyLimit 8.60319402 -> 8.60319402
sellLimit 8.60319402 -> 8,603194
1.0.4 from Maven repo

**Comment by CCob** [comment]
Ah yes, I see.  Thanks for the report.  Should be using Double's toString on sell too.  I'll updated develop and publish a new 1.0.5-SNAPSHOT.  Should be available within the next half hour.

**Comment by CCob** [comment]
I've pushed commit 6552d35 which should fix that issue.  I've published a new 1.0.5-SNAPSHOT which should have that commit it it.  Let me know if that works for you.

**Comment by LowSkiII** [comment]
Yeah, it should works proper now.

**Comment by CCob** [comment]
I'll close this now.  1.0.5 should be released in the next week or so.  For now you can use 1.0.5-SNAPSHOT.  Thanks for reporting!
