### ISSUE TITLE
In  case of disconnection

### ISSUE THREAD

**Issue by cymp** [CCob/bittrex4j#9]
Hello,

What happens in case of disconnection not initiated by the client ? How can we check the connection is alive, and if not, try to reconnect automatically? It happens sometimes that the server closes the connection  so we need to reconnect.

**Comment by CCob** [comment]
Do you mean on the web socket?  Internally it will try an reconnect when socket errors occur or disconnection is detected.  There is also a web socket error handler too.  Off the top of my head I think its the method is onWebsocketError

**Comment by cymp** [comment]
Ok perfect, thank you.
